
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clerq-assessment
    volumes:
      - .:/app
    restart: unless-stopped
    tty: true
    privileged: true
